/* Auto-generated by genmsg_cpp for file /home/xinyan/groovy_workspace/sandbox/hri7633/sensor_streams/cob_people_perception/cob_people_detection_msgs/msg/ColorDepthImage.msg */
#ifndef COB_PEOPLE_DETECTION_MSGS_MESSAGE_COLORDEPTHIMAGE_H
#define COB_PEOPLE_DETECTION_MSGS_MESSAGE_COLORDEPTHIMAGE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "cob_people_detection_msgs/Rect.h"
#include "sensor_msgs/Image.h"
#include "sensor_msgs/Image.h"
#include "cob_people_detection_msgs/Rect.h"

namespace cob_people_detection_msgs
{
template <class ContainerAllocator>
struct ColorDepthImage_ {
  typedef ColorDepthImage_<ContainerAllocator> Type;

  ColorDepthImage_()
  : head_detection()
  , color_image()
  , depth_image()
  , face_detections()
  {
  }

  ColorDepthImage_(const ContainerAllocator& _alloc)
  : head_detection(_alloc)
  , color_image(_alloc)
  , depth_image(_alloc)
  , face_detections(_alloc)
  {
  }

  typedef  ::cob_people_detection_msgs::Rect_<ContainerAllocator>  _head_detection_type;
   ::cob_people_detection_msgs::Rect_<ContainerAllocator>  head_detection;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _color_image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  color_image;

  typedef  ::sensor_msgs::Image_<ContainerAllocator>  _depth_image_type;
   ::sensor_msgs::Image_<ContainerAllocator>  depth_image;

  typedef std::vector< ::cob_people_detection_msgs::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cob_people_detection_msgs::Rect_<ContainerAllocator> >::other >  _face_detections_type;
  std::vector< ::cob_people_detection_msgs::Rect_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::cob_people_detection_msgs::Rect_<ContainerAllocator> >::other >  face_detections;


  typedef boost::shared_ptr< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ColorDepthImage
typedef  ::cob_people_detection_msgs::ColorDepthImage_<std::allocator<void> > ColorDepthImage;

typedef boost::shared_ptr< ::cob_people_detection_msgs::ColorDepthImage> ColorDepthImagePtr;
typedef boost::shared_ptr< ::cob_people_detection_msgs::ColorDepthImage const> ColorDepthImageConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cob_people_detection_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "03f1995e7c816d8ab016aa6ceb57208a";
  }

  static const char* value(const  ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x03f1995e7c816d8aULL;
  static const uint64_t static_value2 = 0xb016aa6ceb57208aULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_people_detection_msgs/ColorDepthImage";
  }

  static const char* value(const  ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Rect head_detection		# bounding box of detected head (coordinates in relation to whole image coordinate system)\n\
sensor_msgs/Image color_image	# color image patch at bounding box head_detection\n\
sensor_msgs/Image depth_image	# depth image patch at bounding box head_detection\n\
Rect[] face_detections		# faces detected in color image inside the head's bounding box (coordinates in relation to head's bounding box)\n\
\n\
================================================================================\n\
MSG: cob_people_detection_msgs/Rect\n\
int32 x\n\
int32 y\n\
int32 width\n\
int32 height\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of cameara\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.head_detection);
    stream.next(m.color_image);
    stream.next(m.depth_image);
    stream.next(m.face_detections);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ColorDepthImage_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cob_people_detection_msgs::ColorDepthImage_<ContainerAllocator> & v) 
  {
    s << indent << "head_detection: ";
s << std::endl;
    Printer< ::cob_people_detection_msgs::Rect_<ContainerAllocator> >::stream(s, indent + "  ", v.head_detection);
    s << indent << "color_image: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.color_image);
    s << indent << "depth_image: ";
s << std::endl;
    Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "  ", v.depth_image);
    s << indent << "face_detections[]" << std::endl;
    for (size_t i = 0; i < v.face_detections.size(); ++i)
    {
      s << indent << "  face_detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cob_people_detection_msgs::Rect_<ContainerAllocator> >::stream(s, indent + "    ", v.face_detections[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MSGS_MESSAGE_COLORDEPTHIMAGE_H

