(cl:defpackage cob_people_detection-srv
  (:use )
  (:export
   "RECOGNITIONTRIGGER"
   "<RECOGNITIONTRIGGER-REQUEST>"
   "RECOGNITIONTRIGGER-REQUEST"
   "<RECOGNITIONTRIGGER-RESPONSE>"
   "RECOGNITIONTRIGGER-RESPONSE"
   "FINISHRECORDING"
   "<FINISHRECORDING-REQUEST>"
   "FINISHRECORDING-REQUEST"
   "<FINISHRECORDING-RESPONSE>"
   "FINISHRECORDING-RESPONSE"
   "CAPTUREIMAGE"
   "<CAPTUREIMAGE-REQUEST>"
   "CAPTUREIMAGE-REQUEST"
   "<CAPTUREIMAGE-RESPONSE>"
   "CAPTUREIMAGE-RESPONSE"
  ))

