/* Auto-generated by genmsg_cpp for file /home/xinyan/groovy_workspace/sandbox/hri7633/sensor_streams/cob_people_perception/cob_people_detection/msg/updateDataAction.msg */
#ifndef COB_PEOPLE_DETECTION_MESSAGE_UPDATEDATAACTION_H
#define COB_PEOPLE_DETECTION_MESSAGE_UPDATEDATAACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "cob_people_detection/updateDataActionGoal.h"
#include "cob_people_detection/updateDataActionResult.h"
#include "cob_people_detection/updateDataActionFeedback.h"

namespace cob_people_detection
{
template <class ContainerAllocator>
struct updateDataAction_ {
  typedef updateDataAction_<ContainerAllocator> Type;

  updateDataAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  updateDataAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::cob_people_detection::updateDataActionGoal_<ContainerAllocator>  _action_goal_type;
   ::cob_people_detection::updateDataActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::cob_people_detection::updateDataActionResult_<ContainerAllocator>  _action_result_type;
   ::cob_people_detection::updateDataActionResult_<ContainerAllocator>  action_result;

  typedef  ::cob_people_detection::updateDataActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::cob_people_detection::updateDataActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::cob_people_detection::updateDataAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_people_detection::updateDataAction_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct updateDataAction
typedef  ::cob_people_detection::updateDataAction_<std::allocator<void> > updateDataAction;

typedef boost::shared_ptr< ::cob_people_detection::updateDataAction> updateDataActionPtr;
typedef boost::shared_ptr< ::cob_people_detection::updateDataAction const> updateDataActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cob_people_detection::updateDataAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cob_people_detection::updateDataAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cob_people_detection

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cob_people_detection::updateDataAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cob_people_detection::updateDataAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cob_people_detection::updateDataAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f7ca18c811ae67ebed8cd0d90e57ae34";
  }

  static const char* value(const  ::cob_people_detection::updateDataAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf7ca18c811ae67ebULL;
  static const uint64_t static_value2 = 0xed8cd0d90e57ae34ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_people_detection::updateDataAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cob_people_detection/updateDataAction";
  }

  static const char* value(const  ::cob_people_detection::updateDataAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cob_people_detection::updateDataAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
updateDataActionGoal action_goal\n\
updateDataActionResult action_result\n\
updateDataActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: cob_people_detection/updateDataActionGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
updateDataGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: cob_people_detection/updateDataGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Updates data in the training database\n\
#\n\
# goal message\n\
int32 update_mode			# update the label with new_label either for 1=one image given the update_index, 2=all entries labeled with old_label\n\
int32 update_index			# the database entry with this index number shall be updated with a new label\n\
string old_label			# all database entries carrying this label are to be updated with new_label\n\
string new_label			# the new label that is supposed to replace the old one\n\
\n\
================================================================================\n\
MSG: cob_people_detection/updateDataActionResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
updateDataResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: cob_people_detection/updateDataResult\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# result message\n\
\n\
================================================================================\n\
MSG: cob_people_detection/updateDataActionFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
updateDataFeedback feedback\n\
\n\
================================================================================\n\
MSG: cob_people_detection/updateDataFeedback\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback message\n\
\n\
\n\
";
  }

  static const char* value(const  ::cob_people_detection::updateDataAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cob_people_detection::updateDataAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct updateDataAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_people_detection::updateDataAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cob_people_detection::updateDataAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::cob_people_detection::updateDataActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::cob_people_detection::updateDataActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::cob_people_detection::updateDataActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // COB_PEOPLE_DETECTION_MESSAGE_UPDATEDATAACTION_H

